---
#add some custome Hombrew taps
- name: Add some custom Homebrew taps
  homebrew_tap:
    name: railwaycat/emacsmacport
    state: present

#install my favourite Homebrew packages
- name: Install my favourite packages via Homebrew
  homebrew:
    update_homebrew: yes
    name: "{{ homebrew_packages }}"
    state: latest

#clone Spacemacs repo & create symlink for Emacs
- name: Clone Spacemacs Git repo
  git:
    repo: https://github.com/syl20bnr/spacemacs
    dest: ~/.emacs.d

#add Emacs symlink to Applications folder
- name: Creating Emacs symlink
  shell: ln -s /usr/local/Cellar/emacs-mac/*/Emacs.app /Applications
