---
- name: Remove all crap from Dock
  shell: dockutil --remove '{{ item }}'
  ignore_errors: true
  with_items: ['{{ dockitems_to_remove }}']

- name: Add items to Dock
  shell: >
    dockutil --find '{{ item.name }}' || dockutil --add '{{ item.path }}'
    && dockutil --move '{{ item.name }}' --position '{{ item.pos }}'
  with_items: ['{{ dockitems_to_persist }}']
