---

- name: Place encfslogin file in home directory
  copy:
    src: encfslogin.sh
    dest: ~/encfslogin.sh

- name: Source dotfiles from GitHub (1/2)
  git:
    repo: 'https://github.com/mick-m/boxconfig.git'
    dest: /tmp/dotfiles

- name: Source dotfiles from GitHub (2/2)
  file:
    path: /tmp/dotfiles/.git
    state: absent

- name: Place dotfiles in my home directory
  copy:
    src: /tmp/dotfiles/
    dest: ~/

- name: Cleanup temporary dotfiles directory
  file:
    path: /tmp/dotfiles/
    state: absent
